dist: trusty

language: php

env:
  global:
    - PHPUNIT_FLAGS="-v -c phpunit.xml --testsuite only_fast_tests"

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COVERAGE=false

    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v -c phpunit.xml --testsuite only_fast_tests --format=php-clover coverage.clover"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction

before_script:
  - sudo apt-get install p7zip-full
  - composer validate --no-check-lock

script:
  - vendor/bin/phpunit -v -c phpunit.xml --testsuite only_fast_tests --coverage-clover=coverage.clover

after_success:
  - if [[ $COVERAGE = true ]]; wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $COVERAGE = true ]]; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
