language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -y zipalign

before_script:
  - composer install

script:
  - composer validate --no-check-lock
  - vendor/bin/phpunit -v --tap -c bootstrap.xml