language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

addons:
  code_climate:
    repo_token: 486a09d58d663450146c53c81c6c64938bcf3bb0b7c8ddebdc125fe97c18213a

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get install -y p7zip-full

before_script:
  - composer install

script:
  - composer validate --no-check-lock
  - vendor/bin/phpunit -v -c bootstrap.xml