sudo: false

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - sudo apt-get install p7zip-full -y
  - sudo apt-get install zipalign -y
  - composer install

script:
  - composer validate --no-check-lock
  - vendor/bin/phpunit -v --tap -c bootstrap.xml