dist: trusty

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction

before_script:
  - sudo apt-get install p7zip-full

script:
  - composer validate --no-check-lock
  - vendor/bin/phpunit -v -c phpunit.xml --testsuite only_fast_tests --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
